name: 部署到 GitHub Pages

on:
  # 每次推送到 main 分支时触发部署
  push:
    branches: [main]
  # 允许手动触发部署
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: 安装依赖
        run: |
          pnpm install
          pnpm add sharp
      - name: 构建
        run: pnpm build
      - name: 设置 Pages
        uses: actions/configure-pages@v3
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2